Fixed adding deleted products
InvTrack/invtrack pull request #211
Opened 2024-06-18 12:58 UTC by Honsiu

Fixes #210

2024-06-18 20:59 UTC, michalstruck requested changes

2024-06-18 20:59 UTC, michalstruck commented on admin/src/routes/(authenticated)/recipes/Parts.svelte
> +          genericUpdate(supabase.from("recipe_part").delete().match({ product_id }), {
I think this would delete all `recipe_part` records that have a matching `product_id` - so would result in data loss across unrelated recipes. Let's not do that 😇😅
We should match by `recipe_part.id`

2024-06-18 20:59 UTC, michalstruck commented on admin/src/routes/(authenticated)/recipes/Parts.svelte
> +  $: console.log({ parts, newParts, deleteParts });
Let's get rid of console logs

2024-06-18 20:59 UTC, michalstruck commented on admin/src/routes/(authenticated)/recipes/Parts.svelte
> +    parts = parts.filter((part) => part.product_id !== partToDelete.product_id && part.id == null);
I know that I requested the `&& part.id == null` check in person, but maybe let's revisit if it's really needed.
This would only filter out if the part came from the backend right? (`part.id` is only present in backend data)

2024-06-19 09:28 UTC, Honsiu commented on admin/src/routes/(authenticated)/recipes/Parts.svelte
> +          genericUpdate(supabase.from("recipe_part").delete().match({ product_id }), {
Right, I'll switch it back

2024-06-19 09:43 UTC, Honsiu commented on admin/src/routes/(authenticated)/recipes/Parts.svelte
> +    parts = parts.filter((part) => part.product_id !== partToDelete.product_id && part.id == null);
Yeah, now when i checked it results in removing all parts that were newly added (cause untill they're written into db they don't have id) 😵‍💫

2024-06-19 10:22 UTC, michalstruck approved these changes

2024-06-19 10:22 UTC, merged